### ISSUE TITLE
SIGSEGV occur during store.newIterator

### ISSUE THREAD

**Issue by shinwing** [chermenin/spark-states#12]
In the commit method, the store.close method is called. But spark will then call the iterator method, and a coredump will occur during store.newIterator ().   
   
spark: 2.4.3   
scala:  2.11   
rocksDB:  5.18.4   
   
    

```
...
INFO RocksDbStateStoreProvider: Saved snapshot for version 7 in ...
INFO RocksDbStateStoreProvider: Committed version 7 for RocksDbStateStore....
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f234b97d978, pid=21272, tid=0x00007f234ad40700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni-linux64.so+0x1bd978]  rocksdb_iterator_helper(rocksdb::DB*, rocksdb::ReadOptions, rocksdb::ColumnFamilyHandle*)+0x18
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data0/hs_err_pid21272.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

**Comment by shinwing** [comment]
under  "complate" mode.

**Comment by chermenin** [comment]
Hi @shinwing Could you try to use the latest versions of the libraries? And is it possible to look at the code example that leads to this?

**Comment by shinwing** [comment]
Thanks for reply.

Do you mean the latest version of rocksDB? 5 5.18.4 is the latest version of 5, I might try it with version 6.

The test program is just a simple wordcount. When I use the append mode, another problem occurs. The destructor reports an error. When destructing, the reference count is not 0. I think this should be caused by iterator not being closed.

I made the following changes to circumvent this issue.
![image](https://user-images.githubusercontent.com/30149563/77979133-651c4080-7336-11ea-9be1-981a49c97f67.png)

When I executed the program, I found that a large number of database files were generated (I did not set ttl). Is this normal?
