### ISSUE TITLE
[question] Accessing StateStore content for inspection

### ISSUE THREAD

**Issue by redsk** [chermenin/spark-states#15]
Hi guys, first of all, thanks for the amazing job!

I'm using `spark-states` for a structured streaming query. I would like to access the content of the state store to inspect what I'm actually storing in the state. Doing so indirectly by checking the output is hard for my use case. The query would be stopped and the access would be read only, I do not intend to modify the data in any way, basically just convert it to `Dataset`/`DataFrame` for further assumption testing. 

I see there's a `def iterator(): Iterator[UnsafeRowPair]` method in `RocksDbStateStore` but I'm unsure how to get a reference to current `RocksDbStateStore` object(s).

Cheers!

**Comment by redsk** [comment]
Answering my own question: the entire state is loaded in the driver but it's totally fine for my purpose.

```scala

import scala.reflect.runtime.universe._

import org.apache.hadoop.fs.{FileSystem, Path}
import ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateStoreProvider

import org.apache.spark.sql.catalyst.encoders.{ExpressionEncoder, encoderFor}
import org.apache.spark.sql.execution.streaming.state._
import org.apache.spark.sql.internal.SQLConf
import org.apache.spark.sql.{DataFrame, Encoder, SparkSession}


class StateExposer[S: Encoder](spark: SparkSession) {

  import spark.implicits._

  def getKeyEncoder[K: Encoder](func: _ => K): ExpressionEncoder[K] =
    encoderFor[K].resolveAndBind()

  def getKeysAndState[K: Encoder](
    checkpointBase: String,
    queryName: String,
    groupByKeyFunc: _ => K,
    storeVersion: Long = Long.MaxValue,
  ): Seq[(K, S)] = {

    val sqlConf: SQLConf = SQLConf.get
    val stateStoreConf: StateStoreConf = StateStoreConf(sqlConf)

    val fs = FileSystem.get(spark.sparkContext.hadoopConfiguration)
    val statePath = new Path(new Path(checkpointBase, queryName), "state")
    val partitions = fs.listStatus(new Path(statePath, "0")).map(_.getPath.getName.toInt)

    val valueEncoder = encoderFor[S]
    val keyEncoder = getKeyEncoder(groupByKeyFunc)

    partitions
      .map { part =>
        val stateStoreId = StateStoreId(statePath.toString, 0L, part)
        val provider = new RocksDbStateStoreProvider()
        provider.init(
          stateStoreId,
          keyEncoder.schema,
          valueEncoder.schema,
          None,
          stateStoreConf,
          spark.sparkContext.hadoopConfiguration
        )
        provider.getStore(storeVersion)
      }
      .flatMap { store =>
        FlatMapGroupsWithStateExecHelper
          .createStateManager(
            encoderFor[UrlState].asInstanceOf[ExpressionEncoder[Any]],
            shouldStoreTimestamp = false,
            stateFormatVersion = 2
          )
          .getAllState(store)
          .map(stateData =>
            (keyEncoder.fromRow(stateData.keyRow), stateData.stateObj.asInstanceOf[S])
          )
      }
  }

  def getKeysAndStateDF[K: Encoder](
    checkpointBase: String,
    queryName: String,
    groupByKeyFunc: _ => K,
    storeVersion: Long = Long.MaxValue,
  )(implicit tagK: TypeTag[K], tagS: TypeTag[S]): DataFrame =
    getKeysAndState(checkpointBase, queryName, groupByKeyFunc, storeVersion)
      .toDF("key", "state")
}
```

**Comment by HeartSaVioR** [comment]
FYI, there's a project (DISCLAIMER: I'm the author) providing state as a data source and let Spark be able to read and rewrite in parallelized way (as it works for batch query).

https://github.com/HeartSaVioR/spark-state-tools

**Comment by redsk** [comment]
@HeartSaVioR Oh that's brilliant! I wish I had find it by googling. Unfortunately, your project is not listed in spark packages, so I missed it. (And I use Scala 2.12)

**Comment by HeartSaVioR** [comment]
Ah OK I had to register it to spark-packages. I’m not also familiar with Scala package distribution so not easy to cross-compiled binaries. (That said, I’ll probably use Scala 2.12 for Spark 3 version line, but not Scala 2.13.)

Actually I’ve proposed the same feature to Apache Spark, though it hasn’t been getting tractions. The ideal way to go is native support.
