### ISSUE TITLE
Rocks DB with spark 3.2

### ISSUE THREAD

**Issue by itsmesrds** [chermenin/spark-states#19]
can we use spark 3.2 rocks db state provider ? can you please provide the example in this repo ? and better we can list down the differences as well

Thanks

**Comment by ivandjuricic** [comment]
Any chance for update of this package to support this?

**Comment by chermenin** [comment]
There is a built-in state store provider based on RocksDB since Spark 3.2: https://spark.apache.org/docs/3.2.0/structured-streaming-programming-guide.html#rocksdb-state-store-implementation
